kernel:
  image: linuxkit/kernel:4.14.62
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: rngd
    image: linuxkit/rngd:v0.6
    command: ["/sbin/rngd", "-1"]    
    cgroupsPath: systemreserved/rngd  
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mounts
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: getty
    image: linuxkit/getty:v0.6
    env:
     - INSECURE=true
    cgroupsPath: systemreserved/getty
  - name: rngd
    image: linuxkit/rngd:v0.6
    cgroupsPath: systemreserved/rngd
  - name: ntpd
    image: linuxkit/openntpd:v0.6
    cgroupsPath: systemreserved/ntpd
  - name: sshd
    image: linuxkit/sshd:v0.6
    cgroupsPath: systemreserved/sshd
  - name: kubelet
    image: linuxkit/kubelet:bcff9a97b3ecaf204ca7ee122f5a071a3dc97d4c
    cgroupsPath: podruntime/kubelet
  - name: bootstrap
    image: puppet/bootstrap:latest
    cgroupsPath: podruntime/bootstrap
    binds:
      - /run:/run
      - /etc:/etc
      - /var/lib:var/lib
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: /etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: /etc/os-release
    contents: |
      PRETTY_NAME="LinuxKit Kubernetes Project"
  - path: /usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: /etc/kubeadm/
    directory: true
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: /etc/cni/net.d
    directory: true
  - path: /opt/cni/bin
    directory: true
  - path: root/.ssh/authorized_keys
    source: ../ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
    - library
