FROM golang:1.9.4-alpine3.7

WORKDIR /go/src/github.com/puppetlabs/kreamlet

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/kream github.com/puppetlabs/kreamlet \
    && CGO_ENABLED=0 GOOS=darwin go build -o ./bin/kream-darwin github.com/puppetlabs/kreamlet
